# Created 2026-02-06 Fri 20:11
#+title: Emacs/Prelude configuration
#+author: Jesse Ernest Oldroyd
#+property: header-args :results output silent

This file describes my =Emacs= configuration, which is built on top of
[[https://github.com/bbatsov/prelude?tab=readme-ov-file][Prelude]]. This file currently focuses on including resources for creating notes
with Org mode, particularly via =org-noter= and =org-roam=. Support for BibTeX
will be provided by [[https://github.com/emacs-citar/citar?tab=readme-ov-file][citar]], [[https://github.com/emacs-citar/citar-org-roam][citar-org-roam]] and =org-cite=.  This is also based in
part on Prot's Emacs configuration, which uses ~org-babel-tangle~ to produce
~.el~ files instead of loading one potentially large ~.org~ file.  See [[https://github.com/protesilaos/dotfiles/blob/master/emacs/.emacs.d/prot-emacs.org][this
Github page]].  This command needs to be re-run each time the configuration
changes.

The following block must be evaluated each time the configuration is updated, as
it produces the actual =.el= files required for my Emacs configuration.
#+begin_src emacs-lisp :tangle "no" :results code
  ;; Add lexical binding to tangled files.  Taken from
  ;; https://emacs.stackexchange.com/questions/81540/lexical-binding-in-a-tangled-init-el-file
  (defun my-ensure-lexical-binding-cookie()
      (goto-char(point-min)) ;; beginning of tangled code
    (insert ";; -*- coding: utf-8; lexical-binding: t -*-")
    (newline)
    (newline)
    (let ((inhibit-message t)) ;; Don't show messages from these functions
      (basic-save-buffer)
      (kill-buffer) nil))
  (add-hook 'org-babel-post-tangle-hook #'my-ensure-lexical-binding-cookie)

  (org-babel-tangle)

  (org-export-to-file 'org "README.org")
#+end_src

I use Emacs with native compilation myself.  This process is relatively
painless, and I use the following commands after cloning Emacs from an
appropriate repo, such as [[https://github.com/emacs-mirror/emacs][emacs-mirror]] on GitHub, although I'm considering
switching to this modified [[https://github.com/jdtsmith/emacs-mac][emacs-mac]] build on macOS:
#+begin_src bash :tangle "no" :results code
  # From within emacs/
  ./autogen.sh
  ./configure --with-native-compilation --with-tree-sitter \
              --without-compress-install --with-imagemagick \
              --with-mailutils --with-xml2 \
              --with-x-toolkit=lucid # GTK and emacs daemon have problems
  make -j8 # or some other appropriate number of cores
  sudo make install
#+end_src
See [[https://www.masteringemacs.org/article/how-to-get-started-tree-sitter][Mastering Emacs]] for a good breakdown of this process.
* General settings and packages
** =Emacs= settings
General settings for =emacs=.
#+begin_src emacs-lisp :tangle "general-settings.el"
  ;; On Windows, commands like rgrep appear to use the wrong "find" command:
  ;; https://stackoverflow.com/questions/3918341/find-parameter-format-not-correct
  (when (eq system-type 'windows-nt)
    (setq find-program "C:\\msys64\\usr\\bin\\find.exe"))

  (use-package emacs
    :init
    (setq user-full-name "Jesse Ernest Oldroyd"))

  ;; macOS-specific config
  (use-package emacs
    :if (eq system-type 'darwin)
    :init
    (setq trash-directory "~/.Trash"))

  ;; Windows-specific config
  (use-package emacs
    :if (eq system-type 'windows-nt)
    :init
    (setq find-program "C:\\msys64\\usr\\bin\\find.exe"))

  ;; The following are taken from Prot's basic config at
  ;; https://protesilaos.com/codelog/2024-11-28-basic-emacs-configuration/
  (use-package modus-themes
    :ensure t
    :config
    (load-theme 'modus-vivendi-tinted :no-confirm-loading))

  (use-package nerd-icons
    :ensure t)

  (use-package nerd-icons-completion
    :ensure t
    :after marginalia
    :config
    (add-hook 'marginalia-mode-hook #'nerd-icons-completion-marginalia-setup))

  (use-package nerd-icons-dired
    :ensure t
    :hook
    (dired-mode . nerd-icons-dired-mode))

  (use-package dired
    :ensure nil
    :commands (dired)
    :hook
    ((dired-mode . dired-hide-details-mode)
     (dired-mode . hl-line-mode))
    :config
    (setq dired-recursive-copies 'always)
    (setq dired-recursive-deletes 'always)
    (setq delete-by-moving-to-trash t)
    (setq dired-dwim-target t))

  (use-package dired-subtree
    :ensure t
    :after dired
    :bind
    ( :map dired-mode-map
      ("<tab>" . dired-subtree-toggle)
      ("TAB" . dired-subtree-toggle)
      ("<backtab>" . dired-subtree-remove)
      ("S-TAB" . dired-subtree-remove))
    :config
    (setq dired-subtree-use-backgrounds nil))

  (use-package trashed
    :ensure t
    :commands (trashed)
    :config
    (setq trashed-action-confirmer 'y-or-n-p)
    (setq trashed-use-header-line t)
    (setq trashed-sort-key '("Date deleted" . t))
    (setq trashed-date-format "%Y-%m-%d %H:%M:%S"))
#+end_src
** UI and navigation settings
See karthink's [[https://karthinks.com/software/avy-can-do-anything/][blog post]] for ideas on using Avy and its associated
commands.  I'm also including =casual= for its menus, which are based on
=transient=.
#+begin_src emacs-lisp :tangle "general-settings.el" :results silent
  ;; Enables highlighted lines.
  (global-hl-line-mode 1)
  (set-face-foreground 'highlight nil)

  ;; Prelude hides the toolbar, so turn it back on with code below.
  ;; (tool-bar-mode 1)

  ;; Toggle whitespace visibility
  (use-package whitespace
    :diminish)

  ;; Default to fullscreen. Taken from
  ;; https://stackoverflow.com/questions/78245398/how-can-i-make-emacsclient-open-in-native-fullscreen-every-time-i-launch-it-fr
  ;; (setq ns-use-native-fullscreen :true)
  ;; (add-to-list 'default-frame-alist '(fullscreen . fullscreen))

  ;; Default to maximized frame.
  (add-to-list 'default-frame-alist '(fullscreen . maximized))

  ;;: Which-key
  ;; Provide keybinding completions.
  (use-package which-key
    :diminish
    :config
    (which-key-mode))

  ;;: Avy bindings
  ;; Override smartparens use of "M-j" so I can use it.
  (with-eval-after-load 'smartparens
    (setq sp-override-key-bindings '(("M-j" . avy-goto-char-time)))
    (sp--update-override-key-bindings))

  (use-package avy
    :ensure t
    :bind (("M-j"   .   avy-goto-char-timer)
           :map isearch-mode-map
           ("M-j"     . avy-isearch)))

  ;;: Casual Suite
  ;; See GitHub configuration for suggested org-agenda binds The agenda
  ;; and calc packages require the use of transient-define-group which
  ;; is not available in the built-in version of transient as of
  ;; <2025-06-03 Tue>. Instead, the upgraded version >= 0.9.0 must be
  ;; downloaded from MELPA.
  (use-package casual
    :ensure t)
  (require 'casual-agenda)
  (keymap-set org-agenda-mode-map "C-o" #'casual-agenda-tmenu)
  (keymap-set org-agenda-mode-map "M-j" #'org-agenda-clock-goto) ; optional
  (keymap-set org-agenda-mode-map "J" #'bookmark-jump) ; optional

  (require 'casual-bookmarks)
  (keymap-set bookmark-bmenu-mode-map "C-o" #'casual-bookmarks-tmenu)
  (keymap-set bookmark-bmenu-mode-map "J" #'bookmark-jump)
  (easy-menu-add-item global-map '(menu-bar)
                      casual-bookmarks-main-menu
                      "Tools")
  (add-hook 'bookmark-bmenu-mode-hook #'hl-line-mode)

  (require 'casual-calc)
  (keymap-set calc-mode-map "C-o" #'casual-calc-tmenu)
  (keymap-set calc-alg-map "C-o" #'casual-calc-tmenu)

  (require 'casual-calendar)
  (keymap-set calendar-mode-map "C-o" #'casual-calendar)

  (require 'casual-dired) ; optional if using autoloaded menu
  (keymap-set dired-mode-map "C-o" #'casual-dired-tmenu)

  (require 'casual-ibuffer)
  (keymap-set ibuffer-mode-map "C-o" #'casual-ibuffer-tmenu)
  (keymap-set ibuffer-mode-map "F" #'casual-ibuffer-filter-tmenu)
  (keymap-set ibuffer-mode-map "s" #'casual-ibuffer-sortby-tmenu)
  ;; # Info
  (require 'casual-info)
  (keymap-set Info-mode-map "C-o" #'casual-info-tmenu)
  ;; Use web-browser history navigation bindings
  (keymap-set Info-mode-map "M-[" #'Info-history-back)
  (keymap-set Info-mode-map "M-]" #'Info-history-forward)
  ;; Bind p and n to paragraph navigation
  (keymap-set Info-mode-map "p" #'casual-lib-browse-backward-paragraph)
  (keymap-set Info-mode-map "n" #'casual-lib-browse-forward-paragraph)
  ;; Bind h and l to navigate to previous and next nodes
  ;; Bind j and k to navigate to next and previous references
  (keymap-set Info-mode-map "h" #'Info-prev)
  (keymap-set Info-mode-map "j" #'Info-next-reference)
  (keymap-set Info-mode-map "k" #'Info-prev-reference)
  (keymap-set Info-mode-map "l" #'Info-next)
  ;; Bind / to search
  (keymap-set Info-mode-map "/" #'Info-search)
  ;; Set Bookmark
  (keymap-set Info-mode-map "B" #'bookmark-set)

  (add-hook 'Info-mode-hook #'hl-line-mode)
  (add-hook 'Info-mode-hook #'scroll-lock-mode)

  (require 'casual-isearch)
  (keymap-set isearch-mode-map "C-o" #'casual-isearch-tmenu)

  (require 'casual-re-builder)
  (keymap-set reb-mode-map "C-o" #'casual-re-builder-tmenu)
  (keymap-set reb-lisp-mode-map "C-o" #'casual-re-builder-tmenu)

  ;;: Modeline
  ;; Taken from
  ;; https://github.com/MatthewZMD/.emacs.d?tab=readme-ov-file#doom-modeline
  (use-package doom-modeline
    :custom
    ;; Don't compact font caches during GC. Windows Laggy Issue
    (inhibit-compacting-font-caches t)
    (doom-modeline-minor-modes t)
    (doom-modeline-icon t)
    (doom-modeline-major-mode-color-icon t)
    (doom-modeline-height 15)
    :config
    (doom-modeline-mode))

  ;; Diminish will help keep the modeline clean via :diminish keyword
  (use-package diminish
    :ensure t)

  ;;: Scrolling
  ;;Later versions of Emacs support pixel scrolling, so we
  ;; can make use of that.  This is WSL specific since emacs-mac has its
  ;; own scrolling setup.
  (when (eq system-type 'gnu/linux)
    (pixel-scroll-precision-mode 1))
#+end_src
** Keybinds
We need to tell emacs how to interpret certain keys on MacBook
keyboards. While we're at it, we'll set up some useful keybinds for moving
through paragraphs.  Of particular note here is the use of [[https://github.com/meow-edit/meow/tree/master][meow-mode]] for
modal editing.  This mode has several minor modes associated with it and
default minor modes can be set via the ~meow-mode-state-list~ variable.
#+begin_src emacs-lisp :tangle "general-settings.el"
  ;; macOS bindings assume use of karabiner to remap caps lock and
  ;; return to control.  Note that Prelude already defines the fn key to
  ;; act as a hyper key, and that control cannot be rebound without
  ;; overwriting karabiner binds.
  (when (eq system-type 'darwin)
    (setq mac-command-modifier 'meta
          ;; mac-command-modifier 'hyper
          mac-option-modifier 'super
          mac-control-modifier 'control))

  (global-set-key "\M-p" 'backward-paragraph)
  (global-set-key "\M-n" 'forward-paragraph)

  ;; Prelude uses S-arrow for windmove keybindings which conflicts with org-mode
  ;; basics. Therefore we use C-arrow prefix instead. On macOS this appears to
  ;; only work with right-command, as left-control (on laptop) has different
  ;; result.
  (windmove-default-keybindings 'ctrl)

  ;; For use with MacBook trackpad. This allows the track pad to be used with
  ;; fly spell-mode. This uses Option+click for Mouse-2 and Cmd+click for
  ;; mouse-3.
  (setq mac-emulate-three-button-mouse t)

  ;; Meow-mode setup.
  ;; (require 'meow)
  (use-package meow
    :ensure t
    ; We already have special icons for Meow from Doom Modeline
    :diminish meow-insert-mode
    :diminish meow-normal-mode
    :diminish meow-beacon-mode
    :diminish meow-motion-mode
    :custom (meow-expand-hint-remove-delay 2.0))

  (defun meow-setup ()
    (interactive)
    (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
    (meow-motion-define-key
     '("j" . meow-next)
     '("k" . meow-prev)
     '("/" . consult-line))
    '("<escape>" . ignore)
    (meow-leader-define-key
     ;; SPC j/k will run the original command in MOTION state.
     '("j" . "H-j")
     '("k" . "H-k")
     '("/" . "H-/")
     ;; Use SPC (0-9) for digit arguments.
     '("1" . meow-digit-argument)
     '("2" . meow-digit-argument)
     '("3" . meow-digit-argument)
     '("4" . meow-digit-argument)
     '("5" . meow-digit-argument)
     '("6" . meow-digit-argument)
     '("7" . meow-digit-argument)
     '("8" . meow-digit-argument)
     '("9" . meow-digit-argument)
     '("0" . meow-digit-argument)
     '("/" . meow-keypad-describe-key)
     '("?" . meow-cheatsheet))
    (meow-normal-define-key
     '("0" . meow-expand-0)
     '("9" . meow-expand-9)
     '("8" . meow-expand-8)
     '("7" . meow-expand-7)
     '("6" . meow-expand-6)
     '("5" . meow-expand-5)
     '("4" . meow-expand-4)
     '("3" . meow-expand-3)
     '("2" . meow-expand-2)
     '("1" . meow-expand-1)
     '("-" . negative-argument)
     '(";" . meow-reverse)
     '("," . meow-inner-of-thing)
     '("." . meow-bounds-of-thing)
     '("[" . meow-beginning-of-thing)
     '("]" . meow-end-of-thing)
     '("a" . meow-append)
     '("A" . meow-open-below)
     '("b" . meow-back-word)
     '("B" . meow-back-symbol)
     '("c" . meow-change)
     '("d" . meow-delete)
     '("D" . meow-backward-delete)
     '("e" . meow-next-word)
     '("E" . meow-next-symbol)
     '("f" . meow-find)
     '("F" . avy-goto-char-timer)
     '("g" . meow-cancel-selection)
     '("G" . meow-grab)
     '("h" . meow-left)
     '("H" . meow-left-expand)
     '("i" . meow-insert)
     '("I" . meow-open-above)
     '("j" . meow-next)
     '("J" . meow-next-expand)
     '("k" . meow-prev)
     '("K" . meow-prev-expand)
     '("l" . meow-right)
     '("L" . meow-right-expand)
     '("m" . meow-join)
     '("n" . meow-search)
     '("o" . meow-block)
     '("O" . meow-to-block)
     '("p" . meow-yank)
     '("q" . meow-quit)
     '("Q" . meow-goto-line)
     '("r" . meow-replace)
     '("R" . meow-swap-grab)
     '("s" . meow-kill)
     '("t" . meow-till)
     '("u" . meow-undo)
     '("U" . meow-undo-in-selection)
     '("v" . meow-visit)
     '("w" . meow-mark-word)
     '("W" . meow-mark-symbol)
     '("x" . meow-line)
     '("X" . meow-goto-line)
     '("y" . meow-save)
     '("Y" . meow-sync-grab)
     '("z" . meow-pop-selection)
     '("/" . avy-goto-char-timer)
     '("'" . repeat)
     '("<escape>" . ignore)))

  ;; Testing out Colemak on my Mac
  (defun meow-setup-colemak ()
    (interactive)
    (setq meow-cheatsheet-layout meow-cheatsheet-layout-colemak)
    (meow-motion-define-key
     ;; Use e to move up, n to move down.
     ;; Since special modes usually use n to move down, we only overwrite e here.
     '("e" . meow-prev)
     '("<escape>" . ignore))
    (meow-leader-define-key
     '("?" . meow-cheatsheet)
     '("1" . meow-digit-argument)
     '("2" . meow-digit-argument)
     '("3" . meow-digit-argument)
     '("4" . meow-digit-argument)
     '("5" . meow-digit-argument)
     '("6" . meow-digit-argument)
     '("7" . meow-digit-argument)
     '("8" . meow-digit-argument)
     '("9" . meow-digit-argument)
     '("0" . meow-digit-argument))
    (meow-normal-define-key
     '("0" . meow-expand-0)
     '("1" . meow-expand-1)
     '("2" . meow-expand-2)
     '("3" . meow-expand-3)
     '("4" . meow-expand-4)
     '("5" . meow-expand-5)
     '("6" . meow-expand-6)
     '("7" . meow-expand-7)
     '("8" . meow-expand-8)
     '("9" . meow-expand-9)
     '("-" . negative-argument)
     '(";" . meow-reverse)
     '("," . meow-inner-of-thing)
     '("." . meow-bounds-of-thing)
     '("[" . meow-beginning-of-thing)
     '("]" . meow-end-of-thing)
     '("/" . meow-visit)
     '("a" . meow-append)
     '("A" . meow-open-below)
     '("b" . meow-back-word)
     '("B" . meow-back-symbol)
     '("c" . meow-change)
     '("e" . meow-prev)
     '("E" . meow-prev-expand)
     '("f" . meow-find)
     '("F" . avy-goto-char-timer)
     '("g" . meow-cancel-selection)
     '("G" . meow-grab)
     '("h" . meow-left)
     '("H" . meow-left-expand)
     '("i" . meow-right)
     '("I" . meow-right-expand)
     '("j" . meow-join)
     '("k" . meow-kill)
     '("l" . meow-line)
     '("L" . meow-goto-line)
     '("m" . meow-mark-word)
     '("M" . meow-mark-symbol)
     '("n" . meow-next)
     '("N" . meow-next-expand)
     '("o" . meow-block)
     '("O" . meow-to-block)
     '("p" . meow-yank)
     '("q" . meow-quit)
     '("r" . meow-replace)
     '("s" . meow-insert)
     '("S" . meow-open-above)
     '("t" . meow-till)
     '("u" . meow-undo)
     '("U" . meow-undo-in-selection)
     '("v" . meow-search)
     '("w" . meow-next-word)
     '("W" . meow-next-symbol)
     '("x" . meow-delete)
     '("X" . meow-backward-delete)
     '("y" . meow-save)
     '("z" . meow-pop-selection)
     '("'" . repeat)
     '("<escape>" . ignore)))

  ;; Meow hints are disabled in Org mode by default. Since I only use
  ;; fixed-width fonts and the same size, this shouldn't be an
  ;; issue. This can be done by removing org-mode from the variable
  ;; meow-expand-exclude-mode-list.

  ;; LaTeX settings for meow. Taken from
  ;; https://aatmunbaxi.netlify.app/comp/configuring_meow_friendly_latex/
  (meow-thing-register 'inline-math
                       '(pair ("\\(") ("\\)"))
                       '(pair ("\\(") ("\\)") ) )

  (add-to-list 'meow-char-thing-table '(?m . inline-math))

  ;; Default states for modes
  (add-to-list 'meow-mode-state-list '(mu4e-main-mode . insert))
  (add-to-list 'meow-mode-state-list '(mu4e-view-mode . motion))

  ;; (cond
  ;;  ((eq system-type 'darwin) (meow-setup-colemak))
  ;;  ((eq system-type 'gnu/linux) (meow-setup)))
  (meow-setup)
  (meow-global-mode 1)
#+end_src
** Completion and templates/snippets
We use =vertico= and =yasnippet= from Prelude. These might be redundant.  I'm
also using Marginalia to provide =marginalia-mode= to provide more
information on completions. On top of this, I include Embark for the
=embark-act= function. This also needs to be integrated with Consult which is
provided by Prelude. The configuration for both of these is the suggested
config on GitHub.
#+begin_src emacs-lisp :tangle "completion-settings.el"
  ;; Configure directory extension for vertico to look more like ido.
  (use-package vertico-directory
    :after vertico
    :ensure nil
    ;; More convenient directory navigation commands
    :bind (:map vertico-map
                ("RET" . vertico-directory-enter)
                ("DEL" . vertico-directory-delete-char)
                ("M-DEL" . vertico-directory-delete-word))
    ;; Tidy shadowed file names
    :hook (rfn-eshadow-update-overlay . vertico-directory-tidy))

  ;; Enable YASnippet.
  (use-package yasnippet
    :ensure t
    :diminish yas-minor-mode
    :config
    (yas-global-mode))

  ;; (yas-global-mode 1)

  ;; karthink's code for integrating CDLaTeX with YASnippet.  Taken from
  ;; https://gist.github.com/karthink/7d89df35ee9b7ac0c93d0177b862dadb
  (use-package cdlatex
    :hook ((cdlatex-tab . yas-expand)
           (cdlatex-tab . cdlatex-in-yas-field)
           (org-mode . turn-on-org-cdlatex))
    :diminish cdlatex-mode
    :diminish org-cdlatex-mode
    :config
    (use-package yasnippet
      :bind (:map yas-keymap
                  ("<tab>" . yas-next-field-or-cdlatex)
                  ("TAB" . yas-next-field-or-cdlatex))
      :config
      (defun cdlatex-in-yas-field ()
        ;; Check if we're at the end of the Yas field
        (when-let* ((_ (overlayp yas--active-field-overlay))
                    (end (overlay-end yas--active-field-overlay)))
          (if (>= (point) end)
              ;; Call yas-next-field if cdlatex can't expand here
              (let ((s (thing-at-point 'sexp)))
                (unless (and s (assoc (substring-no-properties s)
                                      cdlatex-command-alist-comb))
                  (yas-next-field-or-maybe-expand)
                  t))
            ;; otherwise expand and jump to the correct location
            (let (cdlatex-tab-hook minp)
              (setq minp
                    (min (save-excursion (cdlatex-tab)
                                         (point))
                         (overlay-end yas--active-field-overlay)))
              (goto-char minp) t))))

      (defun yas-next-field-or-cdlatex nil
        "Jump to the next Yas field correctly with cdlatex active."
        (interactive)
        (if
            (or (bound-and-true-p cdlatex-mode)
                (bound-and-true-p org-cdlatex-mode))
            (cdlatex-tab)
          (yas-next-field-or-maybe-expand)))))

  ;; Try to set up auto-expansion for certain snippets.
  ;; Taken from
  ;; https://www.reddit.com/r/emacs/comments/o5ewqc/is_automatic_snippet_expansion_with_yasnippet/
  (defun my-yas-try-expanding-auto-snippets ()
    (when yas-minor-mode
      (let ((yas-buffer-local-condition ''(require-snippet-condition . auto)))
        (yas-expand))))
  (add-hook 'post-command-hook #'my-yas-try-expanding-auto-snippets)

  ;; Enable LaTeX snippets in org-mode.  See
  ;; https://emacs.stackexchange.com/questions/38429/yasnippets-loading-two-major-modes-org-mode-and-latex
  ;; My snippets are currently in LaTeX-mode, so this might not work...
  (defun my-org-latex-yas ()
    "Activate org and LaTeX yas expansion in org-mode buffers."
    (yas-minor-mode)
    (yas-activate-extra-mode 'latex-mode))

  (add-hook 'org-mode-hook #'my-org-latex-yas)

  ;; Enable rich annotations using the Marginalia package
  (use-package marginalia
    :ensure t
    ;; Bind `marginalia-cycle' locally in the minibuffer.  To make the binding
    ;; available in the *Completions* buffer, add it to the
    ;; `completion-list-mode-map'.
    :bind (:map minibuffer-local-map
                ("M-A" . marginalia-cycle))

    ;; The :init section is always executed.
    :init

    ;; Marginalia must be activated in the :init section of use-package such that
    ;; the mode gets enabled right away. Note that this forces loading the
    ;; package.
    (marginalia-mode))

  (use-package embark
    :ensure t

    :bind
    (("C-." . embark-act)         ;; pick some comfortable binding
     ("C-;" . embark-dwim)        ;; good alternative: M-.
     ("C-h B" . embark-bindings)) ;; alternative for `describe-bindings'

    :init

    ;; Optionally replace the key help with a completing-read interface
    (setq prefix-help-command #'embark-prefix-help-command)

    ;; Show the Embark target at point via Eldoc. You may adjust the
    ;; Eldoc strategy, if you want to see the documentation from
    ;; multiple providers. Beware that using this can be a little
    ;; jarring since the message shown in the minibuffer can be more
    ;; than one line, causing the modeline to move up and down:

    ;; (add-hook 'eldoc-documentation-functions #'embark-eldoc-first-target)
    ;; (setq eldoc-documentation-strategy #'eldoc-documentation-compose-eagerly)

    :config

    ;; Hide the mode line of the Embark live/completions buffers
    (add-to-list 'display-buffer-alist
                 '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                   nil
                   (window-parameters (mode-line-format . none)))))

  ;; Consult users will also want the embark-consult package.
  (use-package embark-consult
    :ensure t ; only need to install it, embark loads it after consult if found
    ;; :hook
    ;; (embark-collect-mode . consult-preview-at-point-mode)
    )
#+end_src
** Shells
Settings for enhancing the shell in emacs. Note that =sage-shell-mode=
requires SageMath, which is tricky to get on Windows.
#+begin_src emacs-lisp :tangle "shell-settings.el"
  ;;  emacs-sage-shell
  (use-package sage-shell-mode
    :ensure t)

  ;; AucTeX keybindings for SageTeX with emacs-sage-shell
  ;; From Github documentation
  (eval-after-load "latex"
    '(mapc (lambda (key-cmd) (define-key LaTeX-mode-map (car key-cmd) (cdr key-cmd)))
           `((,(kbd "C-c s c") . sage-shell-sagetex:compile-current-file)
             (,(kbd "C-c s C") . sage-shell-sagetex:compile-file)
             (,(kbd "C-c s r") . sage-shell-sagetex:run-latex-and-load-current-file)
             (,(kbd "C-c s R") . sage-shell-sagetex:run-latex-and-load-file)
             (,(kbd "C-c s l") . sage-shell-sagetex:load-current-file)
             (,(kbd "C-c s L") . sage-shell-sagetex:load-file)
             (,(kbd "C-c C-z") . sage-shell-edit:pop-to-process-buffer))))
#+end_src
** LLM integration
Emacs has several packages based around the use of AI/LLMs within Emacs
itself.  I make use of karthink's =gptel= [[https://github.com/karthink/gptel][package]] along with Google Gemini.
This will require getting an appropriate API key (NOT saved to this repo,
obviously).
#+begin_src emacs-lisp :tangle "llm-settings.el"
  (require 'gptel)
#+end_src
** Miscellaneous packages and settings
Packages that don't fit anywhere else just yet. Note that ~nroff~ errors on
Windows appear to be caused by the MSYS2 installation of ~aspell~. We need to
tell ~aspell~ where exactly it can find the necessary modes by creating an
appropriate ~config~ file ~~/.aspell.conf~ in the MSYS2/UCRT64 shell. See
[[https://github.com/msys2/MSYS2-packages/issues/2088#issuecomment-1726339967][this post]] for more information.
#+begin_src emacs-lisp :tangle "general-settings.el"
  ;; Enables writegood-mode.
  (use-package writegood-mode
    :ensure t)
  (global-set-key "\C-c\C-wg" 'writegood-mode)

  ;; Set ispell and args for spellchecking
  (setq ispell-program-name "aspell")
  ;;(setq ispell-extra-args '("--lang=en_US"))

  ;; Set flyspell to use mouse-3 instead of mouse-2.
  ;; Taken from
  ;; https://emacs.stackexchange.com/a/32930
  (eval-after-load "flyspell"
    '(progn
       (define-key flyspell-mouse-map [down-mouse-3] #'flyspell-correct-word)
       (define-key flyspell-mouse-map [mouse-3] #'undefined)))

  ;; Tell ispell to chill so it doesn't slow down my buffer.
  ;; Taken from
  ;; https://github.com/syl20bnr/spacemacs/issues/311#issuecomment-215110131
  ;; (with-eval-after-load 'flyspell
  ;;   (require 'flyspell-lazy)
  ;;   (flyspell-lazy-mode 1)
  ;;   (setq ;; Be a little more aggressive than the lazy defaults
  ;;    flyspell-lazy-idle-seconds 2 ;; This scans just the recent changes
  ;;    flyspell-lazy-window-idle-seconds 6 ;; This scans the whole window
  ;;    )
  ;;   )

  ;; Create nice html exports of buffers
  (use-package htmlize
    :ensure t)

  ;; Install vundo package for visual undo framework.
  (use-package vundo
    :ensure t
    :config
    (setq vundo-glyph-alist vundo-unicode-symbols)
    ;; Use `HJKL` VIM-like motion, also Home/End to jump around.
    ;; These bindings are stolen from
    ;; https://www.reddit.com/r/emacs/comments/txwwfi/vundo_is_great_visual_undotree_for_emacs28/

    (define-key vundo-mode-map (kbd "l") #'vundo-forward)
    (define-key vundo-mode-map (kbd "<right>") #'vundo-forward)
    (define-key vundo-mode-map (kbd "h") #'vundo-backward)
    (define-key vundo-mode-map (kbd "<left>") #'vundo-backward)
    (define-key vundo-mode-map (kbd "j") #'vundo-next)
    (define-key vundo-mode-map (kbd "<down>") #'vundo-next)
    (define-key vundo-mode-map (kbd "k") #'vundo-previous)
    (define-key vundo-mode-map (kbd "<up>") #'vundo-previous)
    (define-key vundo-mode-map (kbd "<home>") #'vundo-stem-root)
    (define-key vundo-mode-map (kbd "<end>") #'vundo-stem-end)
    (define-key vundo-mode-map (kbd "q") #'vundo-quit)
    (define-key vundo-mode-map (kbd "C-g") #'vundo-quit)
    (define-key vundo-mode-map (kbd "RET") #'vundo-confirm))

  ;;; Editing and kill ring
  ;; easy-kill provides the easy-kill and easy-mark commands for more
  ;; convenient killing and marking of text in buffers.  Note that the
  ;; default keybindings for the replaced commands are "M-w" and
  ;; "C-M-@", so these keybindings are now used to call the easy-*
  ;; commands.  See the GitHub for the easy-kill package for available
  ;; options, but some convenient ones are given by
  ;;
  ;; M-w w: save word at point
  ;; M-w s: save sexp at point
  ;;
  ;; The selection is automatically saved and can be killed with a
  ;; subsequent use of "C-w".  These can be repeated or applied to an
  ;; integer for a larger selection.  For example, "M-w w w" and "M-w w
  ;; 2" will copy two words.  You can use =/- as well to increase or
  ;; decrease the selection.  A more complete list of bindings is given
  ;; by "M-w ?".
  (use-package easy-kill
    :ensure t)
  (global-set-key [remap kill-ring-save] 'easy-kill)
  (global-set-key [remap mark-sexp] 'easy-mark)

  ;; browse-kill-ring provides functionality to, you guessed it, browse
  ;; the kill ring.  This is included in Emacs Prelude, which binds
  ;; browse-kill-ring to "s-y".  If using a keyboard that doesn't have
  ;; nice a super key (looking at you, Windows), then "C-x @ s" can be
  ;; used instead.
  ;; (use-package browse-kill-ring)

  ;;; Tree-sitter
  ;; Make use of tree-sitter.  Per Mastering Emacs blog, you will need
  ;; to call treesit-install-language-grammar for each language wanted.
  (setq treesit-language-source-alist
        '((bash "https://github.com/tree-sitter/tree-sitter-bash")
          (cmake "https://github.com/uyha/tree-sitter-cmake")
          (css "https://github.com/tree-sitter/tree-sitter-css")
          (elisp "https://github.com/Wilfred/tree-sitter-elisp")
          (go "https://github.com/tree-sitter/tree-sitter-go")
          (html "https://github.com/tree-sitter/tree-sitter-html")
          (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
          (json "https://github.com/tree-sitter/tree-sitter-json")
          (make "https://github.com/alemuller/tree-sitter-make")
          (markdown "https://github.com/ikatyang/tree-sitter-markdown")
          (python "https://github.com/tree-sitter/tree-sitter-python")
          (toml "https://github.com/tree-sitter/tree-sitter-toml")
          (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
          (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
          (yaml "https://github.com/ikatyang/tree-sitter-yaml")))

  ;;; Formatting
  ;; format-all provides code-formatting via third-party tools such as
  ;; Black (for Python) and latexindent (for LaTeX)
  (use-package format-all
    :bind ("C-c M-i" . format-all-buffer)
    :config
    (setq-default format-all-formatters
                  '(("LaTeX" (latexindent "-m")))))

  ;;; Patches
  ;; This package is useful for patching other packages.  I currently
  ;; need it for patching org-msg on WSL.
  ;; (use-package el-patch
  ;;   :ensure t)
#+end_src
* Enhancing modes for files
The packages here improve/replace how emacs handles certain files.
** Language server protocol
A language server protocol (LSP) can be used to provide completions for
various file types including =.tex= files.  Another alternative is to use
=eglot=, which is a built-in package.
#+begin_src emacs-lisp :tangle "lsp-settings.el"
  (use-package lsp-mode
    :init
    ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
    ;; (setq lsp-keymap-prefix "C-c l")
    :hook (;; replace XXX-mode with concrete major-mode(e. g. python-mode)
           (python-mode . lsp-deferred)
           (python-ts-mode . lsp-deferred)
           (latex-mode . lsp-deferred)
           (LaTeX-mode . lsp-deferred)
           ;; if you want which-key integration
           (lsp-mode . lsp-enable-which-key-integration))
    :commands lsp
    :config
    (setq lsp-pylsp-plugins-black-enabled t))

  ;; optionally
  (use-package lsp-ui :commands lsp-ui-mode)
  ;; if you are helm user
  ;; (use-package helm-lsp :commands helm-lsp-workspace-symbol)
  ;; if you are ivy user
  ;; (use-package lsp-ivy :commands lsp-ivy-workspace-symbol)
  ;; (use-package lsp-treemacs :commands lsp-treemacs-errors-list)

  ;; optionally if you want to use debugger
  ;; (use-package dap-mode)
  ;; (use-package dap-LANGUAGE) to load the dap adapter for your language

  ;; Set digestif as lsp server
  (setq lsp-tex-server 'digestif)

  ;; Make Emacs/digestif aware of TeX info paths.
  (add-to-list 'Info-directory-list "/usr/local/texlive/2024/texmf-dist/doc/info")

  ;; Auto-activate ts-modes when available
  ;; (use-package treesit-auto
  ;;   :ensure t
  ;;   :custom
  ;;   (treesit-auto-install 'prompt)
  ;;   :config
  ;;   (treesit-auto-add-to-auto-mode-alist 'all)
  ;;   (global-treesit-auto-mode))
#+end_src
** PDF-tools
The =pdf-tools= package replaces emacs' own DocView mode for viewing PDF
files (and others) within emacs itself. This will need to be configured to
work with AUCTeX below.
#+begin_src emacs-lisp :tangle "pdf-settings.el"
  ;; Taken from
  ;; https://www.reddit.com/r/emacs/comments/gm1c2p/pdftools_installation/
  (use-package pdf-tools
    :ensure t
    :config
    (pdf-tools-install)
    (setq-default pdf-view-display-size 'fit-page))

  ;; Apparently line numbers break horizontal scrolling in PDF Tools.
  ;; Code below taken from
  ;; emacs.stackexchange.com/questions/74317/how-can-i-get-horizontal-scrolling-in-pdfview-to-work
  (defun bugfix-display-line-numbers--turn-on (fun &rest args)
    "Avoid `display-line-numbers-mode' in `image-mode' and related.
  Around advice for FUN with ARGS."
    (unless (derived-mode-p 'image-mode 'docview-mode 'pdf-view-mode)
      (apply fun args)))

  (advice-add 'display-line-numbers--turn-on :around #'bugfix-display-line-numbers--turn-on)
#+end_src
** AUCTeX
These are settings for working with LaTeX documents in emacs. This requires
AUCTeX, which is included with Prelude modules.
#+begin_src emacs-lisp :tangle "latex-settings.el"
  ;; LaTeX-mode settings
  (add-hook 'LaTeX-mode-hook 'visual-line-mode)
  (add-hook 'LaTeX-mode-hook 'flyspell-mode)
  (add-hook 'LaTeX-mode-hook 'turn-on-reftex)

  ;; Smartparens uses M-j for join sexp, but I want to use that for Avy
  ;; instead.
  (add-hook 'LaTeX-mode-hook
            (lambda ()
              (setq sp-override-key-bindings '(("M-j" . avy-goto-char-timer)))
              (sp--update-override-key-bindings)))
  (setq reftex-plug-into-AUCTeX t)

  ;; Enables rainbow-highlighters for LaTeX.
  ;; (add-hook 'LaTeX-mode-hook #'rainbow-delimiters-mode)
  (add-hook 'TeX-mode-hook #'rainbow-delimiters-mode)

  ;; AUCTeX's live preview requires ghostscript, so we tell AUCTeX where to
  ;; find it on macOS. Live preview on Windows is very troublesome, so we
  ;; don't worry about it.
  (when (eq system-type 'darwin)
    (setq preview-gs-command "/usr/local/bin/gs"))


  ;; Change inline math delimiters that AUCTeX and CDLaTeX
  ;; insert from $...$ to \(...\)
  (setq TeX-electric-math (cons "\\(" ""))
  (setq cdlatex-use-dollar-to-ensure-math nil)

  ;; Reset TeX-open/close-quote from Prelude definitions
  (setq TeX-open-quote "``")
  (setq TeX-close-quote "''")

  ;; latexmk settings
  ;; Use Skim as viewer, enable source <-> PDF sync
  ;; make latexmk available via C-c C-c
  ;; Note: SyncTeX is setup via ~/.latexmkrc (see below)
  ;; (add-hook 'LaTeX-mode-hook
  ;;           (lambda ()
  ;;             (push
  ;;              '("latexmk" "latexmk -pdf %s" TeX-run-TeX nil t
  ;;                :help "Run latexmk on file")
  ;;              TeX-command-list)))

  ;; ;; AucTeX and latexmk don't get along on Windows, so don't worry about
  ;; setting up AUCTeX for latexmk on Windows
  ;; (when (eq system-type 'darwin)
  ;; (add-hook 'TeX-mode-hook '(lambda () (setq TeX-command-default "latexmk"))))
  ;; (when (eq system-type 'windows-nt)
  ;;   (add-hook 'TeX-mode-hook
  ;;             (lambda () (setq TeX-command-default LaTeX-command))))

  ;; Prettify symbols in TeX
  (add-hook 'TeX-mode-hook #'prettify-symbols-mode)

  ;; Code below is taken from
  ;; https://emacs.stackexchange.com/questions/19472/how-to-let-auctex-open-pdf-with-pdf-tools
  ;; Use pdf-tools to open PDF files
  (setq TeX-view-program-selection '((output-pdf "PDF Tools"))
        TeX-source-correlate-mode t
        TeX-source-correlate-start-server t
        TeX-source-correlate-method (quote synctex))

  ;; Update PDF buffers after successful LaTeX runs
  (add-hook 'TeX-after-compilation-finished-functions
            #'TeX-revert-document-buffer)

  ;; Allow for easy use of latexdiff.
  (use-package latexdiff
    :ensure t)

  ;; We need to modify sage-shell to accept filepaths with spaces in their
  ;; names. This appears to require modifying
  ;; sage-shell-sagetex:tex-master-maybe.
  (advice-add 'sage-shell-sagetex:tex-master-maybe
              :around #'my-sage-shell-sagetex:tex-master-maybe)
  (defun my-sage-shell-sagetex:tex-master-maybe (sage-shell-sagetex:tex-master-maybe f &optional nondir)
    (let* ((b (get-file-buffer f))
           (tm (when (and (bufferp b)
                          (boundp 'TeX-master))
                 (buffer-local-value 'TeX-master b))))
      (let ((ms (cond ((and tm (stringp tm))
                       (shell-quote-argument (expand-file-name tm (file-name-directory f))))
                      (t f))))
        (if nondir (file-name-nondirectory ms)
          ms))))

  (advice-add 'sage-shell-sagetex:tex-master-maybe
   :filter-return #'shell-quote-argument)
#+end_src

The above fix for =sage-shell-mode= also requires editing
=sage-shell-mode.py= within the package since the fix breaks a path
argument. In particular, we replace ~sage_tex_load~.  =CDLaTeX= also allows
for extensive customizations and abbreviations.
#+begin_src emacs-lisp :tangle "latex-settings.el"
  (add-hook 'LaTeX-mode-hook #'cdlatex-mode)
  (setq cdlatex-math-symbol-alist
        '((?0 ("\\emptyset" "\\varnothing"))))
#+end_src
** =mu4e=
Mail configuration with =emacs=, =mu= and =mu4e=.  Currently in the process
of adapting this for WSL.  For now, this requires installing =mu= via
Homebrew (which installs =mu4e= as well).  Homebrew is available on both
macOS and Linux.  Setting up =mbsync= also required setting an app specific
password for iCloud.

The =mbsync= setup for WSL uses a different approach with the =pass= password
manager.  This involves creating a =gpg= key (currently set to expire after
two years, i.e., on <2027-06-10 Thu>.  Set up details were taken from [[https://www.redhat.com/en/blog/management-password-store][here]]
and [[https://frostyx.cz/posts/synchronize-your-2fa-gmail-with-mbsync][here]].
#+begin_src emacs-lisp :tangle "mail-settings.el"
  (cond
   ((eq system-type 'darwin)
    (setq mu4e-path (expand-file-name "/opt/homebrew/share/emacs/site-lisp/mu/mu4e")))
   ((eq system-type 'gnu/linux)
    (setq mu4e-path (expand-file-name "/usr/local/share/emacs/site-lisp/mu4e"))))

  (use-package mu4e
    :load-path  mu4e-path)

  ;; for sending mails
  (require 'smtpmail)

  ;; we installed this with homebrew
  (setq mu4e-mu-binary (executable-find "mu"))

  ;; this command is called to sync imap servers:
  (setq mu4e-get-mail-command (concat (executable-find "mbsync") " -a"))
  ;; how often to call it in seconds:
  (setq mu4e-update-interval 300)

  ;; save attachment to desktop by default
  ;; or another choice of yours:
  (setq mu4e-attachment-dir "~/attachments")

  ;; rename files when moving - needed for mbsync:
  (setq mu4e-change-filenames-when-moving t)

  ;; Change HTML display for dark color schemes
  (setq shr-color-visible-luminance-min 80)

  ;; Prevent line breaks in emails.  This can look weird on mobile devices.
  (setq mu4e-compose-format-flowed t)
#+end_src
We also need to configure =mu4e= for multiple accounts. This configuration is
adapted from [[https://cachestocaches.com/2017/3/complete-guide-email-emacs-using-mu-and/#configuring-mu4e][this blog post]]. It looks like we need to set ~tls_starttls = on~
in the ~.msmtprc~ file for this to work properly.
#+begin_src emacs-lisp :tangle "mail-settings.el"
  (with-eval-after-load 'mu4e
    (cond
     ((eq system-type 'darwin)
      (setq send-mail-function 'sendmail-send-it
            sendmail-program "/opt/homebrew/bin/msmtp"
            mail-specify-envelope-from t
            message-sendmail-envelope-from 'header
            mail-envelope-from 'header)
      (setq mu4e-contexts
            `( ,(make-mu4e-context
                 :name "gmail"
                 :match-func (lambda (msg) (when msg
                                             (string-prefix-p "/gmail" (mu4e-message-field msg :maildir))))
                 :vars '((mu4e-trash-folder . "/gmail/[Gmail]/Trash")
                         (mu4e-refile-folder . "/gmail/[Gmail]/Archive")
                         (user-mail-address . "math.oldroyd@gmail.com")
                         (mu4e-maildir-shortcuts . ( ("/gmail/INBOX" . ?i)))
                         ))
               ,(make-mu4e-context
                 :name "wvwc-mail"
                 :match-func (lambda (msg) (when msg
                                             (string-prefix-p "/gmail" (mu4e-message-field msg :maildir))))
                 :vars '((mu4e-trash-folder . "/wvwc-mail/[wvwc-mail]/Trash")
                         (mu4e-refile-folder . "/wvwc-mail/[wvwc-mail]/Archive")
                         (user-mail-address . "oldroyd.j@wvwc.edu")
                         (mu4e-maildir-shortcuts . ( ("/wvwc-mail/INBOX" . ?i)))
                         ))
               ,(make-mu4e-context
                 :name "icloud"
                 :match-func (lambda (msg) (when msg
                                             (string-prefix-p "/icloud" (mu4e-message-field msg :maildir))))
                 :vars '(
                         (mu4e-trash-folder . "/icloud/Deleted Messages")
                         (mu4e-refile-folder . "/icloud/Archive")
                         (user-mail-address . "j.oldroyd@icloud.com")
                         (mu4e-maildir-shortcuts . ( ("/icloud/INBOX" . ?i)))
                         ))
               )))
     ((eq system-type 'gnu/linux)
      (setq send-mail-function 'sendmail-send-it
            sendmail-program "/usr/bin/msmtp"
            mail-specify-envelope-from t
            message-sendmail-envelope-from 'header
            mail-envelope-from 'header)
      (setq mu4e-contexts
            `(,(make-mu4e-context
                :name "wvwc-mail"
                :match-func (lambda (msg) (when msg
                                            (string-prefix-p "/gmail" (mu4e-message-field msg :maildir))))
                :vars '((mu4e-trash-folder . "/wvwc-mail/[Gmail]/Trash")
                        (mu4e-refile-folder . "/wvwc-mail/[Gmail]/Archive")
                        (user-mail-address . "oldroyd.j@wvwc.edu")
                        (mu4e-maildir-shortcuts . ( ("/wvwc-mail/INBOX" . ?i)))
                        ))
              ,(make-mu4e-context
                :name "math-gmail"
                :match-func (lambda (msg) (when msg
                                            (string-prefix-p "/gmail" (mu4e-message-field msg :maildir))))
                :vars '((mu4e-trash-folder . "/math-gmail/[Gmail]/Trash")
                        (mu4e-refile-folder . "/math-gmail/[Gmail]/Archive")
                        (user-mail-address . "math.oldroyd@gmail.com")
                        (mu4e-maildir-shortcuts . ( ("/math-gmail/INBOX" . ?i)))
                        ))))
      )))

  ;; Headers can be misaligned with columns in header view, so this code
  ;; from https://www.djcbsoftware.nl/code/mu/mu4e/Known-issues.html
  ;; tries to fix it.
  (add-hook 'mu4e-headers-mode-hook #'my-mu4e-headers-mode-hook)
  (defun my-mu4e-headers-mode-hook ()
    ;; Account for the fringe and other spacing in the header line.
    (header-line-indent-mode 1)
    (push (propertize " " 'display '(space :align-to header-line-indent-width))
          header-line-format)
    ;; Ensure `text-scale-adjust' scales the header line with the headers themselves
    ;; by ensuring the `default' face is in the inheritance hierarchy.
    (face-remap-add-relative 'header-line '(:inherit (mu4e-header-face
                                                      default))))

  ;; Run mu4e-mailing-list-info-refresh to update mailing lists after change
  (add-to-list 'mu4e-user-mailing-lists '(:list-id "tex-live.tug.org"
                                                   :name "TUG"))

  ;; This is taken from 8.2.1 in mu4e manual
  (setq mu4e-headers-fields
        '((:human-date      .  10)
          (:flags           .  4)
          (:from-or-to      .  20)
          (:mailing-list    .  8)
          (:maildir         .  8)
          (:labels          .  8)
          (:thread-subject  .  nil)))
  (setq mu4e-view-fields
        '(:from :date :to :cc :bcc :subject
                :flags  :maildir
                :message-id :labels))
#+end_src
The =org-msg= package, located [[https://github.com/jeremy-compostella/org-msg?tab=readme-ov-file][on GitHub]], allows us to format emails using
the capabilities of Org Mode.  In particular, we can typeset mathematics
using $\LaTeX$ and send (and evaluate!) code snippets using Org Babel.  There
are many options for this package, but one that we can note in particular is
~org-msg-recipient-names~, which allows replies to automatically use a
different name than what is given in "From" section of the message.  This is
handy if students choose to go by a different name than what is on the course
roster.  At the moment, my customizations for this variable are /not/ tracked
by GitHub for privacy reasons.

This code also contains a patch using =el-patch=, see [[https://github.com/radian-software/el-patch][here]], for the
~org-msg-preview~ function.  My WSL setup requires this patch to make the
message preview functionality work as expected because I use a browser in
Windows to preview messages created in Emacs/WSL.
#+begin_src emacs-lisp :tangle "mail-settings.el"
  ;; The following is for integrating with org-msg.
  (setq mail-user-agent 'mu4e-user-agent)
  ;; Config taken from org-msg github page.
  (use-package org-msg
    :ensure t
    :bind (("C-c C-m C-b" . message-goto-bcc)
           ("C-c C-m C-c" . message-goto-cc))
    )

  (setq org-msg-options "html-postamble:nil H:5 num:nil ^:{} toc:nil author:nil email:nil \\n:t tex:dvisvgm"
        org-msg-startup "hidestars indent inlineimages"
        org-msg-greeting-fmt "\nHi%s,\n\n"
        ;;org-msg-recipient-names '(("jeremy.compostella@gmail.com" . "Jérémy"))
        org-msg-greeting-name-limit 3
        org-msg-default-alternatives '((new          . (text html))
                                       (reply-to-html     . (text html))
                                       (reply-to-text     . (text)))
        org-msg-convert-citation t
        org-msg-signature "

  ,#+begin_signature
  --Jesse
  ,#+end_signature"
        )

  (add-hook 'message-mode-hook 'org-msg-mode)

  ;; Disable fill-paragraph in org-msg to allow mu4e to format=flowed
  ;; each message.  See relevant documentation in mu4e block.
  (require 'messages-are-flowing)
  (add-hook 'org-msg-edit-mode-hook 'turn-off-auto-fill)
  (add-hook 'org-msg-edit-mode-hook 'visual-line-mode)
  (add-hook 'org-msg-edit-mode-hook 'messages-are-flowing-use-and-mark-hard-newlines)


  ;; Org-msg be default uses /tmp/ for storing message previews.  This
  ;; is normally not a problem, except that I sometimes use WSL with my
  ;; browser in the Windows filesystem.  Therefore, I need to modify the
  ;; filepath created for the browse-url function.  This uses el-patch
  ;; to modify the original function definition.
  ;; (if (equal system-type 'gnu/linux)
  ;;     (progn
  ;;       (el-patch-feature org-msg)
  ;;       (with-eval-after-load 'org-msg
  ;;         (el-patch-defun org-msg-preview (arg)
  ;;           "Export and display the current OrgMsg buffer.

  ;; It uses the last alternative of the `alternatives' property as the
  ;; alternatives should be listed in increasing order of
  ;; preference.  If this alternative is `html' it calls the
  ;; `browse-url' function to display the exported mail in a
  ;; web browser.  With the prefix argument ARG set, it calls
  ;; `xwidget-webkit-browse-url' instead of `browse-url'.  For
  ;; all other alternatives, it displays the exported result
  ;; in a buffer."
  ;;           (interactive "P")
  ;;           (let* ((preferred (last (org-msg-get-prop "alternatives")))
  ;;                  (alt (caar (org-msg-build-alternatives preferred t))))
  ;;             (cond ((string= (car alt) "text/html")
  ;;                    (save-window-excursion
  ;;                      (let ((browse-url-browser-function
  ;;                             (if arg 'xwidget-webkit-browse-url
  ;;                               browse-url-browser-function))
  ;;                            (tmp-file (make-temp-file "org-msg" nil ".html")))
  ;;                        (with-temp-buffer
  ;;                          (insert (cdr alt))
  ;;                          (write-file tmp-file))
  ;;                        (el-patch-swap
  ;;                          (browse-url (concat "file://" tmp-file))
  ;;                          (browse-url (concat "file://///wsl.localhost/Ubuntu/" tmp-file)))))
  ;;                    (t (with-current-buffer
  ;;                           (get-buffer-create (format "*OrgMsg %s Preview*" (car alt)))
  ;;                         (delete-region (point-min) (point-max))
  ;;                         (insert (cdr alt)))
  ;;                       (display-buffer (current-buffer))))))))))
#+end_src
** Python
Settings for Python programming.  Virtual environments are handled using
=pyvenv= (the Emacs package) in conjunction with =pyenv= (the Python
package).  The Python configuration is adapted from the configuration located
[[https://emacs.stackexchange.com/questions/59905/how-can-i-start-ipython-from-emacs][here]].  Note that using the =IPython= shell causes an issue with the =ef-owl=
theme as errors are highlighted using =ansiyellow= which is almost unreadable
against the background.  This can be dealt with by adjusting =IPython= itself
as described [[https://emacs.stackexchange.com/questions/76652/overlay-makes-text-unreadable-where-does-it-come-from-overlay-face-is-undef][here]], but the jist is that we need to alter the ~bg:ansiyellow~
setting in =core/ultrab.py=.
#+begin_src emacs-lisp :tangle "python-settings.el"
  ;; (use-package pyvenv
  ;;   :ensure nil)

  (use-package python
    :ensure nil
    :mode
    ("\\.py\\'" . python-mode)

    :init
    (setq-default indent-tabs-mode nil)

    :hook
    ((python-mode . smartparens-mode)
     (python-mode . company-mode)
     (python-mode . flycheck-mode)
     (inferior-python-mode . smartparens-mode))

    :config
    (setq python-indent-offset 4
          python-indent-guess-indent-offset-verbose nil
          python-shell-interpreter "python"
          ;; python-shell-interpreter-args "-i --simple-prompt"
          ))
#+end_src
** =hledger=
=hledger= is a plaintext accounting tool that is designed to be run from the
terminal. We use =heldger-mode= and =flycheck-hledger= to support working
with =hledger= journal files in Emacs. These settings are adapted from the
provided configuration for =hledger-mode=.
#+begin_src emacs-lisp :tangle "accounting.el"
  (use-package hledger-mode
    :ensure t
    :after (htmlize)
    :mode ("\\.journal\\'" "\\.hledger\\'")
    :commands hledger-enable-reporting
    :preface
    (defun hledger/next-entry ()
      "Move to next entry and pulse."
      (interactive)
      (hledger-next-or-new-entry)
      (hledger-pulse-momentary-current-entry))

    (defface hledger-warning-face
      '((((background dark))
         :background "Red" :foreground "White")
        (((background light))
         :background "Red" :foreground "White")
        (t :inverse-video t))
      "Face for warning"
      :group 'hledger)

    (defun hledger/prev-entry ()
      "Move to last entry and pulse."
      (interactive)
      (hledger-backward-entry)
      (hledger-pulse-momentary-current-entry))

    :bind (:map hledger-mode-map
                ("C-c j" . hledger-run-command)
                ("M-p" . hledger/prev-entry)
                ("M-n" . hledger/next-entry))
    :init
    (setq hledger-jfile
          (expand-file-name "~/finance/2024.journal"))

    ;; Expanded account balances in the overall monthly report are
    ;; mostly noise for me and do not convey any meaningful information.
    (setq hledger-show-expanded-report nil)

    (when (boundp 'my-hledger-service-fetch-url)
      (setq hledger-service-fetch-url
            my-hledger-service-fetch-url))

    :config
    (add-hook 'hledger-view-mode-hook #'hl-line-mode)

    (add-hook 'hledger-view-mode-hook
              (lambda ()
                (run-with-timer 1 nil
                                (lambda ()
                                  (when (equal hledger-last-run-command
                                               "balancesheet")
                                    ;; highlight frequently changing accounts
                                    (highlight-regexp "^.*\\(Checking\\|cash\\).*$")
                                    (highlight-regexp "^.*Credit\sCard.*$"
                                                      'hledger-warning-face))))))

    (add-hook 'hledger-mode-hook
              (lambda ()
                (make-local-variable 'company-backends)
                (add-to-list 'company-backends 'hledger-company))))

  ;; (use-package hledger-input
  ;;   :ensure t
  ;;   :preface
  ;;   (defun popup-balance-at-point ()
  ;;     "Show balance for account at point in a popup."
  ;;     (interactive)
  ;;     (if-let ((account (thing-at-point 'hledger-account)))
  ;;         (message (hledger-shell-command-to-string
  ;;                   (format " balance -N %s " account)))
  ;;       (message "No account at point")))

  ;;   :config
  ;;   (setq hledger-input-buffer-height 20)
  ;;   (add-hook 'hledger-input-post-commit-hook #'hledger-show-new-balances)
  ;;   (add-hook 'hledger-input-mode-hook #'auto-fill-mode)
  ;;   (add-hook 'hledger-input-mode-hook
  ;;             (lambda ()
  ;;               (make-local-variable 'company-idle-delay)
  ;;               (setq-local company-idle-delay 0.1))))
#+end_src
** Magit
I want to be able to access tracked files via ~j t~ from ~magit-dispatch~.
We need to load these settings after =magit= is loaded, otherwise Emacs
complains about the hook not existing.
#+begin_src emacs-lisp :tangle "magit-settings.el"
  (with-eval-after-load "magit"
    (magit-add-section-hook
     'magit-status-sections-hook
     'magit-insert-tracked-files
     nil
     'append))
#+end_src
** PreTeXt
PreTeXt uses XML markup to produce documents in multiple formats.  Emacs
already had an =nxml-mode= with schema support that we can use with PreTeXt.
For pretty-printing, there is also =sgml-mode= which contains the function
=sgml-pretty-print=.  This is on top of command line utilities such as
~xmllint~ and ~tidy~.
#+begin_src emacs-lisp :tangle "pretext-settings.el"
  ;; ;; fill-paragraph does not respect XML tags, so we use this code adapted from
  ;; ;; https://stackoverflow.com/a/1042118/3901257
  ;; (add-hook 'nxml-mode-hook #'(lambda ()
  ;;                              (setq paragraph-separate "[     ]*\\(//+\\|\\**\\)\\([  ]*\\| <.*>\\)$\\|^\f")
  ;;                              ))

  ;; Custom PreTeXt mode package created by Michael Shulman.  Accessed
  ;; on pretext-support Google Group on Jan 21, 2026:
  ;; https://groups.google.com/g/pretext-support/c/ts2Xcbkyj9k/m/i-cEX-A_CQAJ
  ;; This requires imenu-list and mmm-mode, which are not currently part
  ;; of my config.
  (use-package pretext-mode
    :load-path "personal/packages/"
    :mode "\\.ptx\\'")

  ;; pretext-mode allows for using asy-mode and AUCTeX within a .ptx
  ;; file, so for now we load asy-mode here.
  (use-package asy-mode
    :load-path "/usr/local/texlive/2025/texmf-dist/asymptote/"
    :mode "\\.asy\\'")
#+end_src
** =lean4-mode=
Lean is an automated theorem prover.  This package provides integration
between Lean and Emacs.  Note that =lean4-mode= is not on MELPA, and so must
be installed manually or with =:vc=.
#+begin_src emacs-lisp :tangle "lean-settings.el"
  (use-package lean4-mode
    ;; :defer t
    :commands lean4-mode
    :vc (:url "https://github.com/leanprover-community/lean4-mode.git"
              :rev :last-release)
    ;; Or, if you prefer the bleeding edge version of Lean4-Mode:
    ;; :rev :newest

    ;; Disable Crux binding in favor of Lean infoview.
    :bind (:map prelude-mode-map
                ("C-c C-i" . nil))
    :mode (("\\.lean\\'" . lean4-mode)))
#+end_src
** EPUB files
We can read EPUB files in Emacs using =nov.el=, a [[https://depp.brause.cc/nov.el/][major mode]].  The
configuration here is adapted from the suggestions on the website.
#+begin_src emacs-lisp :tangle "epub-settings.el"
  (use-package nov
    :ensure t)

  (add-hook 'nov-mode-hook 'visual-line-mode)
  (add-hook 'nov-mode-hook 'visual-fill-column-mode)
  (add-hook 'nov-mode-hook 'visual-line-mode)
  (add-hook 'nov-mode-hook 'visual-fill-column-mode)
  (add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode))
#+end_src
* Org mode
** General UI and edit settings
It's easier to read if we limit horizontal text to 80 characters wide.  We
also want to enable flyspell in Org buffers along with LaTeX previews.
CDLaTeX will also be useful for handling \( \LaTeX \) code.  Note that
\(\LaTeX\) snippets have been enabled via an appropriate =.yas-parents= file
in =snippets/org-mode=.
#+begin_src emacs-lisp :tangle "org-settings.el"
  (use-package org
    :hook
    ;; Org mode 80 character limit.  Taken from
    ;; https://emacs.stackexchange.com/questions/35266/org-mode-auto-new-line-at-80th-column
    ((org-mode . (lambda () (setq fill-column 80)))
     (org-mode . auto-fill-mode)))

  (use-package org-modern
    :hook
    ((org-mode . org-modern-mode)
     (org-agenda-finalize . org-modern-agenda)))

  ;; Make Org bullets a little nicer
  ;; (use-package org-bullets
  ;;   :ensure t
  ;;   :after (org)
  ;;   :hook
  ;;   (org-mode . org-bullets-mode))

  ;; Buffer previews and spellcheck
  (setq org-src-fontify-natively t)
  (add-hook 'org-mode-hook 'flyspell-mode)
  (setq org-preview-latex-default-process 'dvipng)

  ;; Default dvipng alist setting caused issues with org LaTeX previews. This
  ;; is fixed by implementing code below, taken from:
  ;; https://emacs.stackexchange.com/questions/57898/getting-latex-preview-to-work-with-org-mode-dvi-not-found
  (let ((png (cdr (assoc 'dvipng org-preview-latex-process-alist))))
    (plist-put png :latex-compiler '("latex -interaction nonstopmode -output-directory %o %F"))
    (plist-put png :image-converter '("dvipng -D %D -T tight -o %O %F"))
    (plist-put png :transparent-image-converter '("dvipng -D %D -T tight -bg Transparent -o %O %F")))

  ;; Set Org-mode indentation
  (setq org-adapt-indentation t)
#+end_src
Be default, =prelude-mode= redefines =M-S-<UP>= and =M-S-<DOWN>= to
=move-text= commands.  This unfortunately overrides org-table keybinds for
inserting rows, so I reset them here.
#+begin_src emacs-lisp :tangle "org-settings.el"
  (use-package org
    :bind (:map org-mode-map
                ("M-S-<up>" . org-table-kill-row)
                ("M-S-<down>" . org-table-insert-row)))
#+end_src
** Agenda and capture settings
Org-agenda is one of the best reasons to become familiar with Org mode.  We
need to set up our agenda files and capture templates/keybinds.  Currently,
the WSL settings require a symlink from the Windows Google Drive folder to
=~/GoogleDrive/=.
#+begin_src emacs-lisp :tangle "org-settings.el"
  ;; This is for key bindings to invoke agenda mode
  (global-set-key "\C-cl" 'org-store-link)
  (global-set-key "\C-ca" 'org-agenda)
  (global-set-key "\C-cc" 'org-capture)
  (global-set-key "\C-cb" 'org-switchb)

  ;; Changes TODO to DONE automatically if children tasks done
  (defun org-summary-todo (n-done n-not-done)
    "Switch entry to DONE when all subentries are done, to TODO otherwise."
    (let (org-log-done org-log-states)   ; turn off logging
      (org-todo (if (= n-not-done 0) "DONE" "TODO"))))

  (add-hook 'org-after-todo-statistics-hook 'org-summary-todo)

  ;; Define TODO sequence and faces.  Based on
  ;; https://whhone.com/posts/org-mode-task-management/
  (setq org-todo-keywords
        '((sequence "TODO(t)" "NEXT(n)" "PROG(p)" "INTR(i)"
                    "|" "CANCELED(c)" "DONE(d)" "WAITING(w)" "SHELVED(s)")))

  (setq org-todo-keyword-faces
        '(("TODO" . org-todo)
          ("NEXT" . (:foreground "#D35400" :weight bold))
          ("INTR" . org-warning)
          ("PROG" . (:foreground "green" :weight bold))
          ("CANCELED" . (:foreground "#7F8CFD" :strike-through t :weight bold))
          ("WAITING" . (:foreground "#8E44AD" :weight bold))
          ("SHELVED" . (:foreground "gray" :weight bold))))

  ;; Define the custom capture templates
  (setq org-capture-templates
        '(("t" "Todo" entry (file org-default-notes-file)
           "* TODO %?\n%u\n%a\n" :clock-in t :clock-resume t)
          ("m" "Meeting" entry (file org-default-notes-file)
           "* MEETING with %? :MEETING:\n%t" :clock-in t :clock-resume t)
          ("d" "Diary" entry (file+datetree "~/org/diary.org")
           "* %?\n%U\n" :clock-in t :clock-resume t)
          ("i" "Idea" entry (file org-default-notes-file)
           "* %? :IDEA: \n%t" :clock-in t :clock-resume t)
          ("f" "Fleeting note" entry  (file org-default-notes-file)
           "* TODO %^{Note title}\nContext: %a\n%?" :empty-lines-before 1 )
          ("n" "Next Task" entry (file+headline org-default-notes-file "Tasks")
           "** NEXT %? \nDEADLINE: %t")))

  ;; Sets up org-mode files for capture/refile.
  (cond
   ((eq system-type 'darwin)
    (setq org-agenda-files '("~/Documents/org"
                             "~/Google Drive/My Drive/org"
                             "~/Sync/beorg"))
    (setq org-default-notes-file
          (expand-file-name "/Users/jesseoldroyd/Documents/org/notes.org")))
   ((eq system-type 'gnu/linux)
    (setq org-agenda-files '("~/org"
                             "~/beorg"))
    (setq org-default-notes-file
          (expand-file-name "~/beorg/inbox.org"))))

  (setq org-refile-targets
        '((nil :maxlevel . 3)
          (org-agenda-files :maxlevel . 3)))
#+end_src
** Note-taking
This config is adapted from the recommended config for [[https://github.com/org-roam/org-roam-bibtex][=org-roam=]]. The
keybinds need to be modified slightly so as not to conflict with Prelude's
=crux= keybinds. To avoid cursing like a sailor, note that =org-roam= is
activated by visiting an appropriate node and then using
~org-roam-buffer-toggle~, which is bound to ~C-c m l~ below. This will
activate another window that shows backlinks for a given node where the point
is.
#+begin_src emacs-lisp :tangle "org-settings.el"
  (use-package org-roam
    :ensure t
    :bind (("C-c m l" . org-roam-buffer-toggle)
           ("C-c m f" . org-roam-node-find)
           ("C-c m g" . org-roam-graph)
           ("C-c m i" . org-roam-node-insert)
           ("C-c m c" . org-roam-capture)
           ;; Dailies for journaling
           ("C-c m j" . org-roam-dailies-capture-today))
    :config
    ;; If you're using a vertical completion framework, you might want a
    ;; more informative completion interface
    (setq org-roam-node-display-template (concat "${title:*} " (propertize "${tags:10}" 'face 'org-tag)))
    (org-roam-db-autosync-mode)
    ;; If using org-roam-protocol
    (require 'org-roam-protocol))

  ;; Set directory for roam notes based on Windows, WSL or Mac.  This
  ;; assumes that a Windows-based Emacs config is making use of iCloud
  ;; Drive.  For WSL, this code has been changed to no longer require
  ;; iCloud Drive.  The intent now is to use rsync to keep org-roam up
  ;; to date between WSL and other machines.

  (cond ((eq system-type 'darwin)
         (setq org-roam-directory "~/Google Drive/My Drive/org/roam"))
        ((eq system-type 'windows-nt)
         (setq org-roam-directory "C:\\Users\\oldroyd.j\\iCloudDrive\\Documents\\org\\roam"))
        ((eq system-type 'gnu/linux)
         (setq org-roam-directory "~/GoogleDrive/org/roam")
         (setq org-roam-graph-viewer
               (lambda (file)
                 (let
                     ((org-roam-graph-viewer "/mnt/c/Program Files/Mozilla Firefox/firefox.exe"))
                   (org-roam-graph--open (concat "file://///wsl$/Ubuntu" file)))))))

  ;; Org-roam templates
  ;;; Notes template based on suggested citar config.
  (setq org-roam-capture-templates
        '(("d" "default" plain
           "%?"
           :target
           (file+head
            "%<%Y%m%d%H%M%S>-${slug}.org"
            "#+title: ${note-title}\n")
           :unnarrowed t)
          ("n" "literature note" plain
           "%?"
           :target
           (file+head
            "%(expand-file-name (or citar-org-roam-subdir \"\") org-roam-directory)/${citar-citekey}.org"
            "#+title: ${citar-citekey} (${citar-date}). ${note-title}.\n#+created: %U\n#+last_modified: %U\n\n* Main idea(s)\n* Key results\n* Questions")
           :unnarrowed t)))

  (use-package org-noter
    :ensure t)
#+end_src
** BibTeX
The location of the bibliography file needs to be set. We can use the
variable =bib-file= which is part of =bib-mode.el=. This might be used by
AUCTeX as well, so why not set it here. The location of the Google Drive file
probably depends on the OS, so we account for that here as well.

For =citar=, we also configure it to work with =org-roam= and =embark=. For
now, a decent workflow seems to be the following:
1. Open a file using ~citar-open~. With the =org-roam= integration, this file
   should ideally be an =org-roam= file. With a fair amount of profanity this
   can be made to happen.
2. In the file just opened, use ~org-noter~ to associate it with the
   corresponding PDF (if it exists). Be sure to add in any relevant
   =org-roam= nodes as well. Using keywords from the article and placing
   corresponding nodes under ~:PROPERTIES:~ (say, with a ~:KEYWORDS:~
   property) for =org-roam= to refer to might be the best approach here.
3. Take any relevant notes on the paper with =org-noter=. Be sure to
   highlight appropriately using ~C-c C-a h~ and place precise notes with
   ~M-i~. Highlighted sections are probably best used for placing notes
   specific to the paper (such as explaining some mathematical computation)
   while annotation with =org-noter= should focus on observations that I wish
   to refer to outside of the paper.
   #+begin_src emacs-lisp :tangle "bibtex-settings.el"
     (use-package bib-mode
       ;; I don't want to load this just yet.  Instead, I'll set
       ;; OS-specific variables first.
       :defer t
       :if (eq system-type 'darwin)
       :custom
       (bib-file '("~/Google Drive/My Drive/research/library.bib"
                   "~/Documents/zotero/library.bib")))

     (use-package bib-mode
       ;; I don't want to load this just yet.  Instead, I'll set
       ;; OS-specific variables first.
       :defer t
       :if (eq system-type 'gnu/linux)
       :custom
       (bib-file '("~/GoogleDrive/research/My Library.bib"
                   "~/GoogleDrive/research/library-time_scales.bib"
                   "~/GoogleDrive/research/library-tight_frames-association_schemes.bib"
                   "~/GoogleDrive/research/library-tight_frames-algorithms.bib")))

     (use-package org
       :custom
       (org-cite-global-bibliography bib-file)
       (org-cite-insert-processor 'citar)
       (org-cite-follow-processor 'citar)
       (org-cite-activate-processor 'citar))

     (use-package citar
       ;; I don't want to load this just yet.  Instead, I'll set
       ;; OS-specific variables first.
       :defer t
       :if (eq system-type 'darwin)
       :custom
       (citar-library-paths '("~/Google Drive/My Drive/research"
                              "~/Documents/zotero"))
       (citar-notes-paths '("~/Google Drive/My Drive/research")))

     (use-package citar
       ;; I don't want to load this just yet.  Instead, I'll set
       ;; OS-specific variables first.
       :defer t
       :if (eq system-type 'gnu/linux)
       :custom
       (citar-library-paths '("~/GoogleDrive/research"))
       (citar-notes-paths '("~/GoogleDrive/research")))

     (use-package citar
       :ensure t
       :diminish
       :custom
       (citar-bibliography org-cite-global-bibliography)
       :hook
       (LaTeX-mode . citar-capf-setup)
       (org-mode . citar-capf-setup))

     ;; (use-package citar
     ;;   :ensure t
     ;;   :custom
     ;;   (citar-bibliography bib-file)
     ;;   (org-cite-global-bibliography bib-file)
     ;;   (org-cite-insert-processor 'citar)
     ;;   (org-cite-follow-processor 'citar)
     ;;   (org-cite-activate-processor 'citar)
     ;;   :config (require 'org-roam)
     ;;   :hook
     ;;   (LaTeX-mode . citar-capf-setup)
     ;;   (org-mode . citar-capf-setup))

     (use-package citar-org-roam
       :ensure t
       :diminish
       :custom
       (citar-org-roam-capture-template-key "n")
       :after (org-roam citar)
       :config (citar-org-roam-mode))

     (use-package citar-embark
       :ensure t
       :diminish
       :after (citar embark)
       :no-require
       :config (citar-embark-mode))
   #+end_src
** =org-babel= settings
We need to configure =org-babel= for evaluation of ~SRC~ blocks in Org mode.
#+begin_src emacs-lisp :tangle "org-settings.el"
  (use-package gnuplot
    :ensure t
    :defer t)

  (org-babel-do-load-languages
   'org-babel-load-languages '((octave . t) (gnuplot . t)))
#+end_src
*** =ox-hugo=
We can use =ox-hugo= to quickly generate and preview websites created using
Hugo.  This is currently on the backburner since I haven't been working on a
website.
#+begin_src emacs-lisp :tangle "hugo-settings.el"
  (use-package ox-hugo
    :ensure t   ; Auto-install the package from Melpa
    :pin melpa
    :after ox)
#+end_src
** Rubric settings
The code below is used to draft rubrics in Org mode.  This code has been
produced using Google Gemini.  This is based on creating a master rubric file
for each assignment within a =students/= directory.  Student files are also
placed here.  The "essentials" are as follows:
1. ~my/org-grading-calculate-score~ will sum up the total points earned or
   lost in a given problem (as marked by a heading) using checkboxes of the
   form ~- [ ] TEXT :: +/-NUM~.  This command is intended to be used on a
   per-problem basis; eventually, I will want to update this to print points
   earned as well.  Currently, this function isn't very useful.
2. Points are added across the questions by placing the block
   =* Total Grade=
   =#+BEGIN: grading-score=
   =Total Score: *0*=
   =#+END:=
   at the end of the rubric.  Whenever points need to be added up, place your
   cursor within the block and evaluate with =C-c C-c=.
3. Create and sync new rubric items to other files within the same
   directory using ~my/org-grading-broadcast-item~.

A basic rubric template is given by the following code:
#+begin_src org :tangle "no" :results code
  ,#+TITLE: Grading - Alice Smith
  ,#+PROPERTY: header-args :exports none :results value

  ,* Problem 1 - Derivatives
    :PROPERTIES:
    :max_points: 10
    :END:

    - [X] Correct method               :: +5
    - [X] Correct final answer         :: +5
    - [ ] Minor algebra mistake        :: -1
    - [ ] Wrong method                 :: -5

    ,#+BEGIN_SRC emacs-lisp
      (my/org-grading-calculate-score)
    ,#+END_SRC

  ,* Problem 2 - Integrals
    :PROPERTIES:
    :max_points: 15
    :END:

    - [X] Correct bounds               :: +5
    - [X] Correct integration          :: +5
    - [ ] Final answer simplified      :: +5
    - [ ] Incorrect bounds             :: -5

    ,#+BEGIN_SRC emacs-lisp
      (my/org-grading-calculate-score)
    ,#+END_SRC

  ,* Total Grade
    ,#+BEGIN: grading-score
    Total Score: *20*
    ,#+END:
#+end_src
The functions ~my/grading-generate-summary-report~ and
~my/grading-master-report~ both require =gnuplot= to produce visualizations
of grading data.  The master report will produce histograms over all rubrics.
These functions can be accessed using =C-c C-g= (mnemonic: [c]ompile
[g]rading).
#+begin_src emacs-lisp :tangle "org-settings.el"
  (defun my/org-grading-calculate-score ()
    "Calculate points in the current subtree based on checked items with '::
  +/-N'.  Returns the total points."
    (interactive)
    (save-excursion
      ;; If we are inside a code block, move out to the parent headline first
      (when (org-in-src-block-p)
        (org-back-to-heading))

      (let ((points 0))
        ;; We limit the search to the current subtree
        (org-narrow-to-subtree)
        (goto-char (point-min))

        ;; Search for lines with checkboxes and ":: value"
        (while (re-search-forward "^[ \t]*- \\[[xX]\\] .* :: \\(.*\\)" nil t)
          (setq points (+ points (string-to-number (match-string 1)))))

        (widen)
        points)))

  (defun org-dblock-write:grading-score (params)
    "Dynamic block to summarize grades."
    (let ((total 0))
      (save-excursion
        (goto-char (point-min))
        (while (re-search-forward "^[ \t]*- \\[[xX]\\] .* :: \\(.*\\)" nil t)
          (setq total (+ total (string-to-number (match-string 1))))))
      (insert (format "Total Score: *%s*" total))))

  (defun my/org-grading-broadcast-item (heading-name item-text points-text)
    "Add ITEM-TEXT to HEADING-NAME in all .org files in the current
  directory."
    ;;(interactive "sHeading Name (exact match): \nsRubric Item (e.g., '- [ ] Foo :: -1'):")
    (interactive (list (read-string "Enter heading name (exact match): " (org-get-heading))
                       (read-string "Rubric item: " "Text")
                       (read-string "Points (include +/-): " "+1")))
    (let ((files (directory-files "." t "\\.org$")))
      (dolist (file files)
        (with-current-buffer (find-file-noselect file)
          (save-excursion
            (goto-char (point-min))
            ;; Find the specific headline
            (if (re-search-forward (format "^\\*+ .*\\b%s\\b" (regexp-quote
                                                               heading-name)) nil t)
                (progn
                  ;; Move to end of this subtree to append the item
                  (org-end-of-subtree)
                  (insert (format "%s%s%s" (progn (org-insert-item t) "") item-text points-text))
                  (save-buffer)
                  (message "Updated %s" (file-name-nondirectory file)))
              (message "Heading '%s' not found in %s" heading-name (file-name-nondirectory
                                                                    file))))))))

  (defun my/grading-generate-summary-report ()
    "Generate a summary grade report from all .org files in the 'students/' directory.
              Calculates scores on the fly and prepares a buffer for PDF export."
    (interactive)
    (let ((files (directory-files "students" t "\\.org$"))
          (results '()))
      ;; 1. Iterate through all student files
      (dolist (file files)
        (with-temp-buffer
          (insert-file-contents file)
          (let ((name "Unknown")
                (total 0))
            ;; Extract Student Name
            (goto-char (point-min))
            (if (re-search-forward "^\\*+ Student: \\(.*\\)" nil t)
                (setq name (match-string 1)))

            ;; Calculate Score (Sum all checked items with ":: points")
            (goto-char (point-min))
            (while (re-search-forward "^[ \t]*- \\[[xX]\\] .* :: \\(.*\\)" nil t)
              (setq total (+ total (string-to-number (match-string 1)))))

            (push (list name total) results))))

      ;; 2. Sort results alphabetically by name
      (setq results (sort results (lambda (a b) (string< (car a) (car b)))))

      ;; 3. Create the Summary Buffer
      (let ((buffer (get-buffer-create "*Grade Summary*")))
        (with-current-buffer buffer
          (erase-buffer)
          ;; Insert Header for PDF Export
          (insert "#+TITLE: Final Grade Report\n")
          (insert "#+DATE: " (format-time-string "%Y-%m-%d") "\n")
          (insert "#+OPTIONS: toc:nil\n")
          (insert "#+LATEX_HEADER: \\usepackage{booktabs}\n\n") ;; Better table formatting

          (insert "* Class Summary\n\n")

          ;; Insert the Table with LaTeX attributes
          (insert "#+ATTR_LATEX: :environment tabular :align l r :booktabs t\n")
          (insert "| Student Name | Total Score |\n")
          (insert "|--------------+-------------|\n")

          (dolist (entry results)
            (insert (format "| %s | %s |\n" (car entry) (cadr entry))))

          ;; Align the table and enable Org mode
          (org-mode)
          (org-table-align)
          (goto-char (point-min)))

        ;; Display the buffer
        (switch-to-buffer buffer))))

  (defun my/grading-distribution-histogram (&optional bin-size)
    "Generate a grade distribution histogram (frequency table) and Gnuplot header.
           BIN-SIZE defaults to 5 if not provided."
    (interactive "nBin size (default 5): ")
    (let ((size (if (or (not bin-size) (zerop bin-size)) 5 bin-size))
          (files (directory-files "students" t "\\.org$"))
          (scores '())
          (max-score 0)
          (frequencies (make-hash-table :test 'eq)))

      ;; 1. Collect all scores
      (dolist (file files)
        (with-temp-buffer
          (insert-file-contents file)
          (let ((total 0))
            ;; Sum checked items
            (goto-char (point-min))
            (while (re-search-forward "^[ \t]*- \\[[xX]\\] .* :: \\(.*\\)" nil t)
              (setq total (+ total (string-to-number (match-string 1)))))
            (push total scores)
            (setq max-score (max max-score total)))))

      ;; 2. Calculate Frequencies
      (dolist (score scores)
        (let* ((bucket-floor (* (/ score size) size))
               (current-count (gethash bucket-floor frequencies 0)))
          (puthash bucket-floor (1+ current-count) frequencies)))

      ;; 3. Output Table and Plot Header
      (with-current-buffer (get-buffer-create "*Grade Distribution*")
        (erase-buffer)
        ;; Gnuplot configuration for a histogram style bar chart
        (insert "#+TITLE: Grade Distribution\n")
        (insert "#+ATTR_LATEX: :width 10cm\n")
        (insert (format "#+PLOT: title:\"Grade Distribution (Bin Size: %d)\" ind:1 type:2d with:boxes set:\"style fill solid\" set:\"yrange [0:]\"\n" size))

        (insert "| Range | Frequency |\n")
        (insert "|-------+-----------|\n")

        ;; Loop through bins from 0 to max-score
        (let ((i 0))
          (while (<= i max-score)
            (let ((count (gethash i frequencies 0))
                  (range-label (format "%d-%d" i (+ i (- size 1)))))
              (insert (format "| %s | %d |\n" range-label count)))
            (setq i (+ i size))))

        (org-mode)
        (org-table-align)
        (display-buffer (current-buffer))
        (message "Press 'C-c \" g' inside the table to generate the graph."))))

  (defun my/grading-master-report (&optional bin-size)
    "Generate a comprehensive Grade Report with distribution graph and student table.
        BIN-SIZE defaults to 5."
    (interactive "nBin size for histogram (default 5): ")
    (let* ((size (if (or (not bin-size) (zerop bin-size)) 5 bin-size))
           (files (directory-files "students" t "\\.org$"))
           (student-data '()) ;; List of (Name . Score)
           (frequencies (make-hash-table :test 'eq))
           (max-score 0))

      ;; --- 1. Data Collection ---
      (dolist (file files)
        (with-temp-buffer
          (insert-file-contents file)
          (let ((name "Unknown") (total 0))
            ;; Extract Name
            (goto-char (point-min))
            (if (re-search-forward "^\\*+ Student: \\(.*\\)" nil t)
                (setq name (match-string 1)))
            ;; Calculate Score
            (goto-char (point-min))
            (while (re-search-forward "^[ \t]*- \\[[xX]\\] .* :: \\(.*\\)" nil t)
              (setq total (+ total (string-to-number (match-string 1)))))

            (push (cons name total) student-data)
            (setq max-score (max max-score total)))))

      ;; --- 2. Statistics & Binning ---
      ;; Sort students alphabetically
      (setq student-data (sort student-data (lambda (a b) (string< (car a) (car b)))))

      ;; Fill histogram buckets
      (dolist (item student-data)
        (let* ((score (cdr item))
               (bucket-floor (* (/ score size) size))
               (current-count (gethash bucket-floor frequencies 0)))
          (puthash bucket-floor (1+ current-count) frequencies)))

      ;; --- 3. Generate Report Buffer ---
      (let ((buffer (get-buffer-create "*Master Course Report*")))
        (with-current-buffer buffer
          (erase-buffer)

          ;; Header
          (insert "#+TITLE: Course Grade Report\n")
          (insert "#+DATE: " (format-time-string "%Y-%m-%d") "\n")
          (insert "#+LATEX_HEADER: \\usepackage{booktabs}\n")
          (insert "#+OPTIONS: toc:nil\n\n")

          ;; Section 1: Distribution Graph
          (insert "* Grade Distribution\n")
          (insert (format "Bin size: %d points\n\n" size))

          (insert "#+NAME: distribution-table\n")
          (insert "| Range | Frequency |\n")
          (insert "|-------+-----------|\n")

          (let ((i 0))
            (while (<= i max-score)
              (let ((count (gethash i frequencies 0))
                    (range-label (format "%d-%d" i (+ i (- size 1)))))
                (insert (format "| %s | %d |\n" range-label count)))
              (setq i (+ i size))))

          (insert "\n#+BEGIN_SRC gnuplot :var data=distribution-table :file grade_dist.png :results graphics file :exports results\n")
          (insert "set title 'Grade Distribution'\n")
          (insert "set style data histograms\n")
          (insert "set style fill solid\n")
          (insert "set yrange [0:*]\n")
          (insert "set boxwidth 0.75\n")
          (insert "set xlabel 'Score Range'\n")
          (insert "set ylabel 'Frequency'\n")
          (insert "plot data using 2:xtic(1) notitle\n")
          (insert "#+END_SRC\n\n")

          ;; Section 2: Student Table
          (insert "* Student Scores\n")
          (insert "#+ATTR_LATEX: :environment tabular :align l r :booktabs t\n")
          (insert "| Student Name | Total Score |\n")
          (insert "|--------------+-------------|\n")
          (dolist (item student-data)
            (insert (format "| %s | %s |\n" (car item) (cdr item))))

          (org-mode)
          (org-table-align)
          (goto-char (point-min)))

        (switch-to-buffer buffer)
        (message "Report generated! Press 'C-c C-e l o' to export to PDF."))))

  (bind-keys :prefix-map my-grading-map
             :prefix "C-c C-g"
             ("b" . my/org-grading-broadcast-item)
             ("s" . my/grading-generate-summary-report)
             ("m" . my/grading-master-report)
             ("c" . my/org-grading-calculate-score))
#+end_src
* Packages to consider adding
** =elfeed=
This looks like a good way to keep track of arXiv papers.
** =org-reveal=
Create ~reveal.js~ based slideshows using Org mode.
** =matlab=mode=
This will be useful for using MATLAB in Org files.
** =org-super-agenda=
This package will improve Org agenda views. See [[https://github.com/alphapapa/org-super-agenda][=org-super-agenda=]].
